import Script from "next/script";
import { NavMenu } from "@shopify/app-bridge-react";
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="shopify-api-key" content="000bf150fe8c2c8a3cb17953668681ed" />
        <Script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" strategy="beforeInteractive"></Script>
        <Script src="https://cdn.shopify.com/shopifycloud/polaris.js" strategy="beforeInteractive"></Script>
      </head>
      <body>
        <NavMenu>
          <Link href="/" rel="home">
            Home
          </Link>
          <Link href="/templates">Templates</Link>
          <Link href="/settings">Settings</Link>
        </NavMenu>
        {children}
      </body>
    </html>
  );
}
